DROP TABLE IF EXISTS FISH;  
CREATE TABLE FISH (  
    id INT AUTO_INCREMENT  PRIMARY KEY,  
    title VARCHAR(5000) NOT NULL,  
    details VARCHAR(5000) NOT NULL,
    imgsrc VARCHAR(5000) NOT NULL,
    count INT NOT NULL
);